services:
  mongodb:
    image: 'mongo:latest'
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: smida
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
    ports:
      - "27017:27017"
    command: >
      bash -c "
      mongod --auth --bind_ip_all
      "
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: smida
    volumes:
      - ./src/main/resources/db/changelog/postgresql:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  smida-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: smida-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
      - postgres
